import Head from 'next/head'
import Navbar from '../components/Navbar';
import UserList from '../components/UserList';
export default function Home() {
  return (
    <div >
      <Head>
        <title>Bet3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <UserList/>
      </main>
    </div>
  );
}
